### PR TITLE
Changed behaviour of `source._open_dataset` to:

### LINKED ISSUE #660: Cannot open coordinate variables from Intake-ESM datastores
### Description

I'd like to include coordinate variables in my Intake-ESM datastore so that they can be searched for and opened like any other variable. However, Intake-ESM currently [only allows opening the xarray `data_vars`](https://github.com/intake/intake-esm/blob/141425be65c25cbb6b78fb1ec0426593d6157948/intake_esm/source.py#L88) from an asset. If I try to open a coordinate variable from my datastore I am returned an empty xarray Dataset.

The obvious fix is to edit the line in the link above to include any `variable in ds`, but there may be a reason I don't understand for why things are done how they are currently.

### What I Did

To reproduce requires a multi-variable catalog that includes a coordinate variable in the lists of variables. E.g. one can edit the first row of `tests/sample-catalogs/multi-variable-catalog.csv` to include `"TLAT"` in the list of variables. Then:

```python
import intake

cat = intake.open_esm_datastore(
    "tests/sample-catalogs/multi-variable-catalog.json",
    columns_with_iterables=["variable"]
)

cat.search(variable="TLAT").to_dask()
```

returns a Dataset that does not contain `"TLAT"`

### Version information: output of `intake_esm.show_versions()`

<details>

INSTALLED VERSIONS
------------------

cftime: 1.6.3
dask: 2024.2.1
fastprogress: 1.0.3
fsspec: 2024.2.0
gcsfs: 2024.2.0
intake: 0.7.0
intake_esm: 2023.6.14.post31+g141425b
netCDF4: 1.6.5
pandas: 2.2.1
requests: 2.31.0
s3fs: 2024.2.0
xarray: 2024.2.0
zarr: 2.17.0

</details>

### PR DESCRIPTION
**Pull request by charles-turner-1**
## Change Summary

Changes discovery of variables in [source._open_dataset]( https://github.com/intake/intake-esm/blob/6ba67e1df72ebbc80b6cd5f78fd73ddb2cee564a/intake_esm/source.py#L41C19-L42C1) to additionally include coordinate variables, with the following behaviour: 
- Only data variables requested & coordinates they depend on are returned if only data variables are requested (no change from previous behaviour).
- Entire dataset (all data & coordinate variables) are returned if no variables are requested (no change from previous behaviour).
- Only requested coordinate variables are returned if only coordinate variables are requested (updated behaviour).
- Data variables requested, coordinates they depend on, and additional requested coordinate variables are returned both data and coordinate variables are requested (updated behaviour)

- Sync fork (`intake_esm/cat.py`)

## Related issue number

Closes #660 

## Checklist

- [x] Unit tests for the changes exist
- [x] Tests pass on CI

### CODE REVIEW

**Comment by andersy005** [comment]
thank you so much for this addition, @charles-turner-1! 

regarding the test failures,  the recent test failures have highlighted the need to revamp our testing infrastructure. one area of focus is reducing our reliance on cloud-based datasets, which are prone to changes without prior notice. additionally, network connectivity glitches often lead to intermittent test failures.

**Comment by charles-turner-1** [comment]
No worries @andersy005 - think this one is ready for review now.

Our infrastructure for interacting with model outputs at ACCESS-NRI builds pretty heavily on intake-esm, so would be happy to assist with identifying/improving flaky tests.

**Comment by charles-turner-1** [comment]
@mgrover1 If you're able to review that would be great

**Review by mgrover1 — APPROVED** [review]
Looks great to me - I like this way of approaching the problem of coordinates and such. We can resolve the doc build issues in additional PRs

**Pull request merged**
