### PR TITLE
Ensure aggregation control is optional

### LINKED ISSUE #549: `aggregation_control` is documented as optional but coded as mandatory in pydantic model
### Description
The `esm-catalog-spec.md` documentation says that the `aggregation_control` field is optional https://github.com/intake/intake-esm/blob/c7cc33474564402096f3f66530828741b660f9e8/docs/source/reference/esm-catalog-spec.md?plain=1#L72 but the pydantic model defines is as mandatory https://github.com/intake/intake-esm/blob/c7cc33474564402096f3f66530828741b660f9e8/intake_esm/cat.py#L114

### PR DESCRIPTION
**Pull request by mgrover1**
## Change Summary

Makes aggregation control optional, matching the catalog spec docs

## Related issue number

Closes #549 

## Checklist

- [x] Unit tests for the changes exist
- [x] Tests pass on CI
- [x] Documentation reflects the changes where applicable

### CODE REVIEW

**Comment by andersy005** [comment]
@mgrover1, thank you for this fix. do you mind adding a unit test?

**Comment by mgrover1** [comment]
You betcha!

**Comment by mgrover1** [comment]
> @mgrover1, thank you for this fix. do you mind adding a unit test?

Done!

**Comment by mgrover1** [comment]
@andersy005 - do you think the error here could be caused by the long run time? RTD is saying it took 363 seconds (60 minutes)

**Review by andersy005 — APPROVED** [review]
this looks solid to me 👍🏽. thank you, @mgrover1

**Pull request merged**
