### PR TITLE
Accept Path in esm_datastore

### LINKED ISSUE #540: Passing Path objects to `esm_datastore`
This is very minor, but I feel we should be able to pass `pathlib.Path` objects to `intake_esm.esm_datastore`.

Currently it fails with:
```
Traceback (most recent call last):
  File "/disk/project/ouracat.py", line 326, in <module>
    ouracat()
  File "/disk/.conda/xscen/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/disk/.conda/xscen/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/disk/.conda/xscen/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/disk/.conda/xscen/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/disk/project/ouracat.py", line 302, in ouracat
    compare_catalogs(json_file, old_json_file, temp_folder)
  File "/disk/project/ouracat.py", line 146, in compare_catalogs
    new = DataCatalog(new_file)
  File "/home/pbourg/Projets/xscen/xscen/catalog.py", line 164, in __init__
    super().__init__(*args, **kwargs)
  File "/disk/.conda/xscen/lib/python3.10/site-packages/intake_esm/core.py", line 88, in __init__
    self.esmcat = ESMCatalogModel.load(
  File "/disk/.conda/xscen/lib/python3.10/site-packages/intake_esm/cat.py", line 223, in load
    _mapper = fsspec.get_mapper(json_file, **storage_options)
  File "/disk/.conda/xscen/lib/python3.10/site-packages/fsspec/mapping.py", line 230, in get_mapper
    fs, urlpath = url_to_fs(url, **kwargs)
  File "/disk/.conda/xscen/lib/python3.10/site-packages/fsspec/core.py", line 392, in url_to_fs
    chain = _un_chain(url, kwargs)
  File "/disk/.conda/xscen/lib/python3.10/site-packages/fsspec/core.py", line 346, in _un_chain
    if "::" in path
TypeError: argument of type 'PosixPath' is not iterable
```

So in fact, the error comes from `fsspec`. I nevertheless feel that `intake_esm` would be the best place to cast the path to string.

### PR DESCRIPTION
**Pull request by aulemahal**
## Change Summary

Cast paths to string before passing to fsspec.

## Related issue number

Fixes #540.

## Checklist

- [x] Unit tests for the changes exist
- [x] Tests pass on CI
- [x] Documentation reflects the changes where applicable

### CODE REVIEW

**Review by andersy005 — APPROVED** [review]
Thank you for this fix, @aulemahal!

**Comment by andersy005** [comment]
It appears this PR is also impacted by the netCDF's thread safety issue reported in https://github.com/intake/intake-esm/pull/548

**Comment by mgrover1** [comment]
@andersy005 - can we set the following

> Folks using `iris` and hitting this issue you can workaround it by setting `dask` to `single-threaded` with:
> 
> ```python
> import dask
> dask.config.set(scheduler="single-threaded")
> ```
> 
> instead of pinning to `netcdf4!=1.6.1`.
 
for now?

**Comment by mgrover1** [comment]
That was mentioned in this issue https://github.com/Unidata/netcdf4-python/issues/1192

**Comment by mgrover1** [comment]
> It appears this PR is also impacted by the netCDF's thread safety issue reported in #548

This has been fixed using the snippet I mentioned before... should be good for review

**Review by mgrover1 — APPROVED** [review]

**Comment by andersy005** [comment]
thank you, @mgrover1 / @aulemahal

**Pull request merged**
