### PR TITLE
Wildcard search documentation

### PR DESCRIPTION
**Pull request by jukent**
Checklist

- [X] Passes `pre-commit run --all-files`
- [ ] Tests added / passed ---- NA for documentation

Address part of PR #277

### CODE REVIEW

**Comment by jukent** [comment]
I'm not sure why the black-formatter tests are failing.

When I run `black --line-length 100 --skip-string-normalization .`
I see `All done! ✨ 🍰 ✨  15 files left unchanged.`

yet the core.py and utils.py keep failing.

**Comment by andersy005** [comment]
Thank you for working on this, @jukent! 

> I'm not sure why the black-formatter tests are failing.

Try running the pre-commit hooks instead of running `black --line-length 100 --skip-string-normalization .`

To run the pre-commit hooks, you will need to install `pre-commit` via `pypi` or `conda` or `homebrew`

Then from the root directory, run `pre-commit install`. To fix the current formatting issue, run the following `pre-commit run --all-files`. 



Regarding the failing tests, don't worry about them. I know why they are broken and I have some local changes to fix them but haven't pushed them to GitHub yet.

**Comment by jukent** [comment]
@andersy005 I had run `pre-commit run --all-files` when I first made the PR and it passed. It changed some files this time, probably because I had been trying to run the black formatter so much.

The formatter test is still failing. I understand that some of the other tests might fail, but this one is confusing to me.

**Comment by andersy005** [comment]
@jukent, I was able to address the inconsistencies in the CI in #280. All tests are now passing. I merged needed changes into the wildcard branch of your fork, and pushed directly to your fork. You will need to update your local clone via `git pull`

**Pull request closed without merging**
