### PR TITLE
Updates for pydantic v2

### LINKED ISSUE #617: Updates needed for pydantic v2
### Description

Pydantic v2 was released on July 1. Intake-ESM uses pydantic, but does not work with pydantic v2. Simply importing Intake-ESM with pydantic=v2.0 results in an error.

A few syntactical updated throughout Intake-ESM should resolve this issue.

### What I Did

```python
# With pydantic=v2.0
import intake_esm
```

gives

```python
~/miniconda3/envs/test/lib/python3.11/site-packages/pydantic/_internal/_config.py:257: UserWarning: Valid config keys have changed in V2:
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda3/envs/test/lib/python3.11/site-packages/intake_esm/__init__.py", line 9, in <module>
    from .core import esm_datastore
  File "~/miniconda3/envs/test/lib/python3.11/site-packages/intake_esm/core.py", line 21, in <module>
    from .cat import ESMCatalogModel
  File "~/miniconda3/envs/test/lib/python3.11/site-packages/intake_esm/cat.py", line 68, in <module>
    class Assets(pydantic.BaseModel):
  File "~/miniconda3/envs/test/lib/python3.11/site-packages/intake_esm/cat.py", line 77, in Assets
    @pydantic.root_validator
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/test/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/test/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.0/u/root-validator-pre-skip
```

### PR DESCRIPTION
**Pull request by dougiesquire**
## Change Summary

This PR implements changes required for Intake-ESM to update to the recently-released pydantic v2. I'd appreciate someone taking a close look at this as I'm not a pydantic expert, especially v2.

## Related issue number

Closes #617 

## Checklist

- [x] Unit tests for the changes exist
- [x] Tests pass on CI

### CODE REVIEW

**Comment by dougiesquire** [comment]
Agh, the `autodoc_pydantic` Sphinx extension does not support pydantic v2 and it doesn't look like it will any time soon, see https://github.com/mansenfranzen/autodoc_pydantic/issues/146.

What to do?

- Update Intake-ESM to use pydantic v2 and lose the `autodoc_pydantic` extension, resulting in the API section of the docs being poorly formatted. (Unfortunately, I can't generate a version of the docs atm to demonstrate what this would look like as the docs rely on ecgtools which also requires pydantic updates - yes, we're in a state right now where Intake-ESM and ecgtools are both failing because the other is failing),
- Pin pydantic to v1 in Intake-ESM.

**Comment by dougiesquire** [comment]
I tried to disable the `autodoc_pydantic` extension and temporarily change the CI doc environment to install ecgtools from https://github.com/ncar-xdev/ecgtools/pull/164 so the docs would build in this PR, but there's another issue with the docs that makes the build fail intermittently.

Instead, here's is a screenshot of the API docs for a pydantic object rendered _without_ the `autodoc_pydantic` extension. I think they look fine. Let me know if you agree and I'll finish up this PR.

Screenshot 2023-07-06 at 10 51 26 pm

**Comment by mgrover1** [comment]
> I tried to disable the `autodoc_pydantic` extension and temporarily change the CI doc environment to install ecgtools from [ncar-xdev/ecgtools#164](https://github.com/ncar-xdev/ecgtools/pull/164) so the docs would build in this PR, but there's another issue with the docs that makes the build fail intermittently.
> 
> Instead, here's is a screenshot of the API docs for a pydantic object rendered _without_ the `autodoc_pydantic` extension. I think they look fine. Let me know if you agree and I'll finish up this PR.
> 
> Screenshot 2023-07-06 at 10 51 26 pm

Thanks so much @dougiesquire for the hard work here - I think this looks fine and we can proceed!

**Comment by dougiesquire** [comment]
Ready for review @mgrover1 

Note, the docs build is still failing because of:

1. the pydantic changes required in ecgtools
2. another intermittent issue when running `docs/source/how-to/build-a-catalog-from-timeseries-files.md`. 

I suggest:

- merge this PR. This should fix the failing tests in https://github.com/ncar-xdev/ecgtools/pull/164
- merge https://github.com/ncar-xdev/ecgtools/pull/164 and do an ecgtools release. This should fix issue 1 above.
- address issue 2 in another PR

**Review by mgrover1 — APPROVED** [review]

**Comment by mansenfranzen** [comment]
@dougiesquire You can now test the new **autodoc_pydantic** version supporting pydantic v2 via `pip install autodoc_pydantic==2.0.0`. The dev docs already showcase v2 support (see [here](https://autodoc-pydantic.readthedocs.io/en/main-2.x/index.html)). Migration guide is available [here](https://autodoc-pydantic.readthedocs.io/en/main-2.x/users/faq.html#migration-guide-from-v1-to-v2).

Any feedback is more than appreciated. The current **autodoc_pydantic** version `2.0.0` on pypi remains yanked for one week until final release.

**Pull request merged**
