### PR TITLE
Ensure fsspec storage options are propagated to `xr.open_dataset`

### PR DESCRIPTION
**Pull request by jukent**
## Change Summary

Fix bug that replaces storage options kwarg with an empty dictionary. Done with @andersy005 

## Checklist

- [x] Unit tests for the changes exist
- [x] Tests pass on CI
- [ ] Documentation reflects the changes where applicable

### CODE REVIEW

**Comment by jukent** [comment]
Should we add a test that makes sure the 'storage_options` kwarg is maintained?

**Comment by andersy005** [comment]
> Should we add a test that makes sure the 'storage_options` kwarg is maintained?

👍🏽  Let's add a simple test in https://github.com/intake/intake-esm/blob/main/tests/test_source.py

**Comment by jukent** [comment]
> 👍🏽 Let's add a simple test in https://github.com/intake/intake-esm/blob/main/tests/test_source.py

SImple test added!

**Review by andersy005 — APPROVED** [review]
Thank you, @jukent!

**Pull request merged**
